"""add application type field

Revision ID: 0eb9c4b830ba
Revises: c1236ee626a3
Create Date: 2025-02-19 20:50:23.401104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eb9c4b830ba'
down_revision: Union[str, None] = 'c1236ee626a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('application_type', sa.Enum('sell', 'rent_out', 'buy', 'rent', name='applicationtypeenum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'application_type')
    # ### end Alembic commands ###
