"""delete user phone number field 

Revision ID: b8738d3b56e4
Revises: 6b9ff56b9b1d
Create Date: 2025-02-19 22:43:01.261346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8738d3b56e4'
down_revision: Union[str, None] = '6b9ff56b9b1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
